"""
Catalogue manager for a collection of Snapshot objects.

Responsibilities (Single Responsibility Principle):
    - Managing the set of snapshots stored under a catalogue directory.
    - Providing CRUD operations (add, delete, get, update, duplicate) on the catalogue.
    - Installing and uninstalling snapshots from their original target locations.
    - Exporting and importing snapshots and the whole catalogue as zip archives.
    - Creating and restoring backup archives (delegating to SnapshotManager).
    - Parsing backup archive filenames to reconstruct SnapshotBackupInfo metadata.

Classes:
    SnapshotCatalogue – High-level catalogue API.
"""

import json
import re
import shutil
import tempfile
import zipfile
from datetime import datetime
from pathlib import Path
from typing import Optional

from pylizlib.core.data.gen import gen_random_string
from pylizlib.core.log.pylizLogger import logger
from pylizlib.core.os.path import remove_directory_or_move_to_temp
from pylizlib.core.os.snap.domain import (
    BackupType,
    SnapDirAssociation,
    SnapEditAction,
    Snapshot,
    SnapshotBackupInfo,
    SnapshotSettings,
)
from pylizlib.core.os.snap.manager import SnapshotManager
from pylizlib.core.os.snap.serializer import SnapshotSerializer
from pylizlib.core.os.snap.utils import SnapshotUtils


class SnapshotCatalogue:
    def __init__(self, path_catalogue: Path, settings: SnapshotSettings = SnapshotSettings()):
        """
        Initializes the catalogue manager for a collection of snapshots.

        Args:
            path_catalogue: The root directory path for the catalogue.
            settings: Global settings to apply to snapshots in this catalogue.
        """
        self.path_catalogue = path_catalogue
        self.settings = settings
        self.path_catalogue.mkdir(parents=True, exist_ok=True)

    @staticmethod
    def _parse_backup_info(backup_path: Path) -> SnapshotBackupInfo:
        """Parses backup metadata from filename conventions generated by create_backup()."""
        stem = backup_path.stem
        created_at = None
        backup_type: BackupType | None = None

        # Expected timestamp suffix: _YYYYMMDD_HHMMSS
        time_match = re.search(r"_(\d{8}_\d{6})$", stem)
        core = stem
        if time_match:
            time_value = time_match.group(1)
            try:
                created_at = datetime.strptime(time_value, "%Y%m%d_%H%M%S")
            except ValueError:
                created_at = None
            core = stem[: time_match.start()]

        if core.endswith("_ad"):
            backup_type = BackupType.ASSOCIATED_DIRECTORIES
            core = core[:-3]
        elif core.endswith("_sd"):
            backup_type = BackupType.SNAPSHOT_DIRECTORY
            core = core[:-3]

        is_export = not core.startswith("backup_")
        payload = core[7:] if core.startswith("backup_") else core

        prefix = payload
        snapshot_id: str | None = None
        if "_" in payload:
            prefix, snapshot_id = payload.rsplit("_", 1)

        return SnapshotBackupInfo(
            path=backup_path,
            file_name=backup_path.name,
            snapshot_id=snapshot_id,
            backup_type=backup_type,
            prefix=prefix,
            created_at=created_at,
            is_export=is_export,
        )

    def list_backups(self, backup_dir: Path) -> list[SnapshotBackupInfo]:
        """
        Returns metadata for every .zip backup in the provided folder.

        Args:
            backup_dir: Folder containing backup archives.

        Returns:
            A list of parsed backup metadata entries sorted by date (newest first).
        """
        if not backup_dir.exists() or not backup_dir.is_dir():
            raise ValueError(f"Provided backup directory '{backup_dir}' is not a valid folder.")

        backups: list[SnapshotBackupInfo] = []
        for zip_path in backup_dir.glob("*.zip"):
            backups.append(self._parse_backup_info(zip_path))

        return sorted(
            backups,
            key=lambda b: (b.created_at is not None, b.created_at or datetime.min, b.file_name),
            reverse=True,
        )

    def restore_backup(self, backup_zip_path: Path):
        """
        Restores a backup archive, auto-detecting the backup type from its filename.

        - `_sd` backups restore the whole snapshot directory into the catalogue.
        - `_ad` backups restore associated directories to their `original_path`.

        Args:
            backup_zip_path: Path of the backup .zip archive.

        Raises:
            ValueError: If the archive path is invalid, backup naming is not recognized,
                        or the restore cannot be performed.
            IOError: If extraction fails.
        """
        if not backup_zip_path.is_file() or backup_zip_path.suffix != ".zip":
            raise ValueError(f"Provided path '{backup_zip_path}' is not a valid .zip file.")

        info = self._parse_backup_info(backup_zip_path)
        if info.backup_type is None:
            raise ValueError(
                "Could not recognize backup type from filename. "
                "Expected suffix '_ad' or '_sd' before timestamp."
            )

        with tempfile.TemporaryDirectory() as temp_dir:
            temp_dir_path = Path(temp_dir)
            try:
                with zipfile.ZipFile(backup_zip_path, "r") as zf:
                    zf.extractall(temp_dir_path)
            except zipfile.BadZipFile:
                raise ValueError(f"File '{backup_zip_path}' is not a valid zip file.")
            except Exception as e:
                raise IOError(f"Failed to extract zip file '{backup_zip_path}': {e}")

            if info.backup_type == BackupType.SNAPSHOT_DIRECTORY:
                json_path = temp_dir_path / self.settings.json_filename
                if not json_path.is_file():
                    raise ValueError(
                        f"Snapshot-directory backup does not contain '{self.settings.json_filename}'."
                    )

                restored_snapshot = SnapshotSerializer.from_json(json_path)
                destination_path = SnapshotUtils.get_snapshot_path(restored_snapshot.id, self.path_catalogue)

                backup_dest = destination_path.with_name(f"{destination_path.name}_bck_{gen_random_string(6)}")
                try:
                    if destination_path.exists():
                        destination_path.rename(backup_dest)
                    shutil.copytree(temp_dir_path, destination_path)
                except Exception as e:
                    logger.error(f"Failed to restore snapshot directory: {e}. Rolling back.")
                    if destination_path.exists():
                        shutil.rmtree(destination_path)
                    if backup_dest.exists():
                        backup_dest.rename(destination_path)
                    raise IOError(f"Failed to restore snapshot directory: {e}") from e
                else:
                    if backup_dest.exists():
                        shutil.rmtree(backup_dest)
                return

            # ASSOCIATED_DIRECTORIES restore
            if not info.snapshot_id:
                raise ValueError("Could not determine snapshot ID from associated-directories backup filename.")

            snapshot = self.get_by_id(info.snapshot_id)
            if not snapshot:
                raise ValueError(
                    f"Snapshot with ID '{info.snapshot_id}' not found. "
                    "Associated-directories restore requires an existing snapshot metadata entry."
                )

            dir_name_to_assoc: dict[str, SnapDirAssociation] = {
                assoc.directory_name: assoc for assoc in snapshot.directories
            }

            # Preflight: collect all targets and validate unambiguously
            tasks = []
            for extracted_dir in temp_dir_path.iterdir():
                if not extracted_dir.is_dir():
                    continue

                candidate = dir_name_to_assoc.get(extracted_dir.name)
                if not candidate:
                    logger.warning(
                        f"No matching associated directory found for backup folder '{extracted_dir.name}'. Skipping."
                    )
                    continue

                destination = Path(candidate.original_path)
                tasks.append({
                    "extracted_dir": extracted_dir,
                    "destination": destination,
                    "backup_dest": destination.with_name(f"{destination.name}_bck_{gen_random_string(6)}")
                })

            if not tasks:
                raise ValueError("No associated directories were restored from the backup archive.")

            # Swap transaction
            completed_rollbacks = []
            try:
                for task in tasks:
                    destination = task["destination"]
                    backup_dest = task["backup_dest"]
                    extracted_dir = task["extracted_dir"]
                    
                    if destination.exists():
                        destination.rename(backup_dest)
                    
                    shutil.copytree(extracted_dir, destination)
                    completed_rollbacks.append(task)
                    
                # Commit successful, delete backups
                for task in tasks:
                    if task["backup_dest"].exists():
                        shutil.rmtree(task["backup_dest"])
            except Exception as e:
                logger.error(f"Failed to restore associated directories: {e}. Rolling back.")
                for task in tasks:
                    destination = task["destination"]
                    backup_dest = task["backup_dest"]
                    if backup_dest.exists():
                        if destination.exists():
                            shutil.rmtree(destination)
                        backup_dest.rename(destination)
                raise IOError(f"Failed to restore associated directories: {e}") from e

    def delete_backup(self, backup_zip_path: Path):
        """
        Deletes a backup archive from the filesystem.

        Args:
            backup_zip_path: Path of the backup .zip archive to delete.

        Raises:
            ValueError: If the path is not a valid .zip file or does not exist.
        """
        if not backup_zip_path.is_file() or backup_zip_path.suffix != ".zip":
            raise ValueError(f"Provided path '{backup_zip_path}' is not a valid .zip file.")
        backup_zip_path.unlink()

    def set_catalogue_path(self, new_path: Path):
        """
        Sets a new path for the snapshot catalogue.
        The directory will be created if it does not exist.

        Args:
            new_path: The new path for the catalogue.
        """
        self.path_catalogue = new_path
        self.path_catalogue.mkdir(parents=True, exist_ok=True)


    def add(self, snap: Snapshot, progress_callback=None, message_callback=None):
        """
        Adds a new snapshot to the catalogue.
        """
        snap_manager = SnapshotManager(snap, self.path_catalogue, self.settings)
        snap_manager.create(progress_callback=progress_callback, message_callback=message_callback)

    def delete(self, snap: Snapshot, message_callback=None):
        """
        Deletes a snapshot from the catalogue.

        If backup settings are enabled, a backup is created before deletion.

        Args:
            snap: The Snapshot object to delete.
        """
        snap_manager = SnapshotManager(snap, self.path_catalogue, self.settings)
        if self.settings.bck_before_delete_enabled:
            snap_manager.create_backup(self.settings.backup_path, "beforeDelete", BackupType.SNAPSHOT_DIRECTORY)
        snap_manager.delete(message_callback=message_callback)

    def get_all(self) -> list[Snapshot]:
        """
        Retrieves all snapshots from the catalogue.

        Returns:
            A list of Snapshot objects found in the catalogue.
        """
        self.path_catalogue.mkdir(parents=True, exist_ok=True)
        snapshots: list[Snapshot] = []
        for current_dir in self.path_catalogue.iterdir():
            if current_dir.is_dir():
                try:
                    snap = SnapshotUtils.get_snapshot_from_path(current_dir, self.settings.json_filename)
                    if snap is not None:
                        snapshots.append(snap)
                except Exception as e:
                    logger.error(f"Failed to load snapshot from {current_dir}: {e}. Skipping corrupted entry.")
        return snapshots

    def get_by_id(self, snap_id: str) -> Optional[Snapshot]:
        """
        Retrieves a single snapshot from the catalogue by its ID.

        Args:
            snap_id: The ID of the snapshot to retrieve.

        Returns:
            The Snapshot object if found, otherwise None.
        """
        all_snaps = self.get_all()
        for snap in all_snaps:
            if snap.id == snap_id:
                return snap
        return None

    def update_snapshot_by_objs(self, old: Snapshot, new: Snapshot, message_callback=None):
        """
        Updates a snapshot by comparing the old and new Snapshot objects.
        It calculates the differences and applies them.

        Args:
            old: The original Snapshot object.
            new: The new Snapshot object with the desired changes.
        """
        edits = SnapshotUtils.get_edits_between_snapshots(old, new)
        self.update_snapshot_by_edits(new, edits, message_callback=message_callback)

    def update_snapshot_by_edits(self, snap: Snapshot, edits: list[SnapEditAction], message_callback=None):
        """
        Updates a snapshot using a pre-computed list of edit actions.

        If backup settings are enabled, a backup is created before the update.

        Args:
            snap: The Snapshot object to update.
            edits: A list of SnapEditAction objects to apply.
        """
        snap_manager = SnapshotManager(snap, self.path_catalogue, self.settings)
        if self.settings.bck_before_modify_enabled:
            snap_manager.create_backup(self.settings.backup_path, "beforeEdit", BackupType.SNAPSHOT_DIRECTORY)
        snap_manager.update_json_base_fields()
        snap_manager.update_json_data_fields()
        snap_manager.update_from_actions_list(edits, message_callback=message_callback)

    def duplicate_by_id(self, snap_id: str, message_callback=None):
        """
        Duplicates a snapshot by its ID.

        Args:
            snap_id: The ID of the snapshot to duplicate.

        Raises:
            ValueError: If no snapshot is found with the given ID.
        """
        snap = self.get_by_id(snap_id)
        if snap is None:
            raise ValueError(f"No snapshot found with ID {snap_id}")
        snap_manager = SnapshotManager(snap, self.path_catalogue, self.settings)
        snap_manager.duplicate(message_callback=message_callback)

    def export_assoc_dirs(self, snap_id: str, destination_path: Path, message_callback=None):
        """
        Exports the associated directories of a snapshot to a zip file.

        Args:
            snap_id: The ID of the snapshot to export.
            destination_path: The folder where the exported zip file will be saved.
        """
        snap = self.get_by_id(snap_id)
        if not snap:
            raise ValueError(f"No snapshot found with ID {snap_id}")

        snap_manager = SnapshotManager(snap, self.path_catalogue, self.settings)
        # Use the existing create_backup method with a specific prefix for export
        snap_manager.create_backup(
            destination_path,
            "export",
            BackupType.ASSOCIATED_DIRECTORIES,
            is_export=True,
            message_callback=message_callback
        )

    def export_snapshot(self, snap_id: str, destination_path: Path, message_callback=None):
        """
        Exports the entire snapshot directory (the internal backup) to a zip file.

        Args:
            snap_id: The ID of the snapshot to export.
            destination_path: The folder where the exported zip file will be saved.
        """
        snap = self.get_by_id(snap_id)
        if not snap:
            raise ValueError(f"No snapshot found with ID {snap_id}")

        snap_manager = SnapshotManager(snap, self.path_catalogue, self.settings)
        snap_manager.create_backup(
            destination_path,
            "export_snap",
            BackupType.SNAPSHOT_DIRECTORY,
            is_export=True,
            message_callback=message_callback
        )

    def export_catalogue(self, destination_path: Path, file_name: str = "catalogue_export.zip"):
        """
        Exports the entire catalogue to a single zip file.

        Args:
            destination_path: The folder where the exported zip file will be saved.
            file_name: The name for the output zip file.
        """
        destination_path.mkdir(parents=True, exist_ok=True)
        zip_path = destination_path.joinpath(file_name)

        snapshots = self.get_all()
        if not snapshots:
            logger.warning("Catalogue is empty. Nothing to export.")
            return

        with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as archive:
            for snap in snapshots:
                snap_dir = self.get_snap_directory_path(snap)
                if snap_dir and snap_dir.is_dir():
                    for file_path in snap_dir.rglob("*"):
                        if file_path.is_file():
                            archive.write(
                                file_path,
                                arcname=file_path.relative_to(self.path_catalogue),
                            )

    def import_catalogue(self, zip_path: Path):
        """
        Imports all snapshots from a catalogue zip file, skipping existing ones.

        Args:
            zip_path: The path to the catalogue .zip file.

        Raises:
            ValueError: If the provided path is not a valid .zip file.
            IOError: If the zip file fails to extract.
        """
        if not zip_path.is_file() or zip_path.suffix != ".zip":
            raise ValueError(f"Provided path '{zip_path}' is not a valid .zip file.")

        with tempfile.TemporaryDirectory() as temp_dir:
            temp_dir_path = Path(temp_dir)

            # 1. Extract the zip to a temporary directory
            try:
                with zipfile.ZipFile(zip_path, "r") as zf:
                    zf.extractall(temp_dir_path)
            except zipfile.BadZipFile:
                raise ValueError(f"File '{zip_path}' is not a valid zip file.")
            except Exception as e:
                raise IOError(f"Failed to extract zip file '{zip_path}': {e}")

            # 2. Iterate through extracted folders and import them
            for potential_snap_dir in temp_dir_path.iterdir():
                if not potential_snap_dir.is_dir():
                    continue

                json_path = potential_snap_dir / self.settings.json_filename
                if not json_path.is_file():
                    logger.warning(f"Skipping directory '{potential_snap_dir.name}' as it does not contain a snapshot json file.")
                    continue

                try:
                    # Read just the ID to avoid loading the whole object unnecessarily
                    data = json.loads(json_path.read_text(encoding="utf-8"))
                    snap_id = data.get("id")
                    if not snap_id:
                        logger.warning(f"Skipping directory '{potential_snap_dir.name}' as snapshot ID is missing from json.")
                        continue

                    # 3. Check for ID conflict
                    if self.exists(snap_id):
                        logger.info(f"Snapshot with ID '{snap_id}' already exists. Skipping import.")
                        continue

                    # 4. Copy the extracted folder to the catalogue
                    destination_path = SnapshotUtils.get_snapshot_path(snap_id, self.path_catalogue)
                    shutil.copytree(potential_snap_dir, destination_path)
                    logger.info(f"Successfully imported snapshot with ID '{snap_id}'.")

                except Exception as e:
                    logger.error(f"Failed to import snapshot from directory '{potential_snap_dir.name}': {e}")

    def import_snapshot(self, zip_path: Path):
        """
        Imports a snapshot from a zip file into the catalogue.

        Args:
            zip_path: The path to the .zip file to import.

        Raises:
            ValueError: If the path is not a valid zip file, if the zip is corrupted,
                        if the snapshot.json is missing, or if a snapshot with the same ID
                        already exists.
            IOError: If the zip file fails to extract.
        """
        if not zip_path.is_file() or zip_path.suffix != ".zip":
            raise ValueError(f"Provided path '{zip_path}' is not a valid .zip file.")

        with tempfile.TemporaryDirectory() as temp_dir:
            temp_dir_path = Path(temp_dir)

            # 1. Extract the zip to a temporary directory
            try:
                with zipfile.ZipFile(zip_path, "r") as zf:
                    zf.extractall(temp_dir_path)
            except zipfile.BadZipFile:
                raise ValueError(f"File '{zip_path}' is not a valid zip file.")
            except Exception as e:
                raise IOError(f"Failed to extract zip file '{zip_path}': {e}")

            # 2. Validate the content and get snapshot
            json_path = temp_dir_path / self.settings.json_filename
            if not json_path.is_file():
                raise ValueError(f"The zip file does not contain a snapshot json file ('{self.settings.json_filename}').")

            try:
                snapshot_to_import = SnapshotSerializer.from_json(json_path)
            except Exception as e:
                raise ValueError(f"Failed to read snapshot data from json: {e}")

            # 3. Check for ID conflict
            if self.exists(snapshot_to_import.id):
                raise ValueError(f"A snapshot with the ID '{snapshot_to_import.id}' already exists in the catalogue.")

            # 4. Copy the extracted folder to the catalogue
            destination_path = SnapshotUtils.get_snapshot_path(snapshot_to_import.id, self.path_catalogue)
            shutil.copytree(temp_dir_path, destination_path)

    def update_assoc_with_installed(self, snap_id: str, message_callback=None):
        """
        Updates the snapshot's internal copy of associated directories
        with the current state of those directories on the filesystem.
        """
        snap = self.get_by_id(snap_id)
        if not snap:
            raise ValueError(f"No snapshot found with ID {snap_id}")

        snap_manager = SnapshotManager(snap, self.path_catalogue, self.settings)
        if self.settings.bck_before_modify_enabled:
            snap_manager.create_backup(self.settings.backup_path, "beforeUpdateLocal", BackupType.SNAPSHOT_DIRECTORY)
        snap_manager.update_associated_dirs_from_system(message_callback=message_callback)

    def remove_installed_copies(self, snap_id: str, message_callback=None):
        """
        Removes the installed copies of a snapshot's associated directories from the system.

        Args:
            snap_id: The ID of the snapshot whose installed copies should be removed.
        """
        snap = self.get_by_id(snap_id)
        if not snap:
            logger.warning(f"Snapshot with ID '{snap_id}' not found. Cannot remove installed copies.")
            return
        snap_manager = SnapshotManager(snap, self.path_catalogue, self.settings)
        snap_manager.remove_installed_copies(message_callback=message_callback)

    def install(self, snap: Snapshot, clear_destination: bool = True, progress_callback=None, message_callback=None):
        """
        Installs a snapshot's contents to their original target locations.

        If backup settings are enabled, a backup of the target locations is created first.

        Args:
            snap: The Snapshot object to install.
            clear_destination: If True, clears the destination directories before copying.
            progress_callback: Optional callback for installation progress.
        """
        snap_manager = SnapshotManager(snap, self.path_catalogue, self.settings)
        if self.settings.bck_before_install_enabled:
            snap_manager.create_backup(
                self.settings.backup_path,
                "preinstall",
                BackupType.ASSOCIATED_DIRECTORIES,
            )
        snap_manager.install(self.settings.install_with_everyone_full_control, clear_destination=clear_destination, progress_callback=progress_callback, message_callback=message_callback)

    def exists(self, snap_id: str) -> bool:
        """
        Checks if a snapshot with the given ID exists in the catalogue.

        Args:
            snap_id: The ID of the snapshot to check.

        Returns:
            True if the snapshot exists, False otherwise.
        """
        return self.get_by_id(snap_id) is not None

    def get_snap_directory_path(self, snap: Snapshot) -> Path | None:
        """
        Gets the filesystem path to a snapshot's storage directory.

        Args:
            snap: The Snapshot object.

        Returns:
            The Path to the snapshot's directory, or None if the snapshot doesn't exist.
        """
        if not self.exists(snap.id):
            return None
        return SnapshotUtils.get_snapshot_path(snap.folder_name, self.path_catalogue)
